//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespuestasEncuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCUESTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCUESTA()
        {
            this.PREGUNTAS = new HashSet<PREGUNTA>();
        }
    
        public int IdEncuesta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string NombreEncuesta { get; set; }
        public string TituloEncuesta { get; set; }
        public string DescripcionEncuesta { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTA> PREGUNTAS { get; set; }
    }
}
