//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespuestasEncuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPUESTA
    {
        public int IdRespuestas { get; set; }
        public Nullable<int> IdPreguntas { get; set; }
        public string respuesta1 { get; set; }
        public string respuesta2 { get; set; }
        public string respuesta3 { get; set; }
        public string respuesta4 { get; set; }
        public string respuesta5 { get; set; }
    
        public virtual PREGUNTA PREGUNTA { get; set; }
    }
}
